# Generated by Django 6.0.5 on 2026-05-26 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_country_currency'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='id_supplier',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Supplier ID'),
        ),
    ]
