# Generated by Django 6.0.5 on 2026-05-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, choices=[('US', 'United States (US)'), ('CN', 'China (CN)'), ('IN', 'India (IN)'), ('JP', 'Japan (JP)'), ('DE', 'Germany (DE)'), ('GB', 'United Kingdom (GB)'), ('FR', 'France (FR)'), ('IT', 'Italy (IT)'), ('CA', 'Canada (CA)'), ('RU', 'Russia (RU)'), ('MX', 'Mexico (MX)'), ('BR', 'Brazil (BR)'), ('AR', 'Argentina (AR)'), ('CL', 'Chile (CL)'), ('CO', 'Colombia (CO)'), ('PE', 'Peru (PE)'), ('VE', 'Venezuela (VE)'), ('EC', 'Ecuador (EC)'), ('BO', 'Bolivia (BO)'), ('UY', 'Uruguay (UY)'), ('PY', 'Paraguay (PY)'), ('CR', 'Costa Rica (CR)'), ('DO', 'Dominican Republic (DO)'), ('GT', 'Guatemala (GT)'), ('HN', 'Honduras (HN)')], max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'United States Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('GBP', 'British Pound Sterling (GBP)'), ('JPY', 'Japanese Yen (JPY)'), ('CNY', 'Chinese Yuan Renminbi (CNY)'), ('CHF', 'Swiss Franc (CHF)'), ('CAD', 'Canadian Dollar (CAD)'), ('BRL', 'Brazilian Real (BRL)'), ('MXN', 'Mexican Peso (MXN)'), ('ARS', 'Argentine Peso (ARS)'), ('CLP', 'Chilean Peso (CLP)'), ('COP', 'Colombian Peso (COP)'), ('PEN', 'Peruvian Sol (PEN)'), ('UYU', 'Uruguayan Peso (UYU)'), ('PYG', 'Paraguayan Guarani (PYG)'), ('BOB', 'Bolivian Boliviano (BOB)'), ('CRC', 'Costa Rican Colon (CRC)'), ('DOP', 'Dominican Peso (DOP)'), ('GTQ', 'Guatemalan Quetzal (GTQ)'), ('HNL', 'Honduran Lempira (HNL)')], max_length=20, verbose_name='Currency'),
        ),
    ]
